#!/bin/bash
# tools/ffmpeg-notice.sh - regenerate licenses/FFmpeg.txt, the notice that travels with the shipped
# FFmpeg DLLs.
#
# Every fact in the output is read out of the binaries, because the notice is a distribution
# obligation and a hand-written one rots: an exe can be handed a different set of DLLs than the tree
# it was built against, and then the repo's claim would be false. The script REFUSES to write a notice
# for a build that is configured --enable-gpl or --enable-nonfree, so the file's existence is itself
# evidence of the check.
#
#   bash tools/ffmpeg-notice.sh         # after tools/get-ffmpeg.sh
set -u
cd /h/wallpaper || exit 1
DIR=${FFMPEG_DIR:-build/ffm-lgpl}
FF="$DIR/bin/ffmpeg.exe"
OUT=licenses/FFmpeg.txt
[ -f "$FF" ] || { echo "no $FF - run tools/get-ffmpeg.sh first"; exit 1; }

VER_ALL=$("$FF" -hide_banner -version 2>&1)
VER_LINE=$(echo "$VER_ALL" | head -1)
# -version, not -buildconf: buildconf prints the flags one per line and no license at all, so parsing it
# here used to yield an empty string - and the "--enable-gpl => REFUSE" check below would then have
# passed vacuously. A guard that cannot fail is not a guard, so the parse result is asserted non-empty.
CONF=$(echo "$VER_ALL" | sed -n 's/^configuration: //p')
[ -n "$CONF" ] || { echo "REFUSE: ffmpeg -version gave no configuration line; the GPL check cannot run"; exit 2; }
# The library's own words about its license, which is what a notice should quote rather than paraphrase.
LICENSE=$("$FF" -hide_banner -L 2>&1)   # left as the library prints it, line breaks and all
if echo "$CONF" | grep -qE -- '--enable-gpl|--enable-nonfree'; then
  echo "REFUSE: this build is not LGPL-shippable:"; echo "  $CONF"; exit 2
fi
# The pinned version and URL live in get-ffmpeg.sh, which is the only place they may be edited, so the
# notice takes them from there instead of repeating them - a literal ${VER} in a legal notice is worse
# than no notice.
eval "$(grep -E '^(VER|URL)=' tools/get-ffmpeg.sh)"
[ -n "${URL:-}" ] || { echo "REFUSE: could not read the pinned URL out of tools/get-ffmpeg.sh"; exit 2; }
# The version line carries the exact upstream commit this archive was built from
# (n9.0.2-22-g46d8f462ee-20261006), which is the "corresponding source" the license asks for.
COMMIT=$(echo "$VER_LINE" | grep -oE 'g[0-9a-f]{7,40}' | head -1 | sed 's/^g//')
SRC_TAG=$(echo "$VER_LINE" | grep -oE 'n[0-9]+\.[0-9]+(\.[0-9]+)?' | head -1)
# The archive itself, if it is still around, plus whatever get-ffmpeg.sh recorded when it fetched it.
ZIP=build/ffm-dl/ffmpeg-lgpl-shared.zip
ZIP_SHA=""
[ -f "$ZIP" ] && ZIP_SHA=$(sha256sum "$ZIP" | cut -d' ' -f1)
[ -z "$ZIP_SHA" ] && [ -f "$ZIP.sha256" ] && ZIP_SHA=$(cat "$ZIP.sha256")
VERSION3=no
echo "$CONF" | grep -q -- "--enable-version3" && VERSION3=yes
if [ "$VERSION3" = yes ]; then
  EFFECTIVE="GNU Lesser General Public License v3 (or later), because the build is configured --enable-version3"
else
  EFFECTIVE="GNU Lesser General Public License v2.1 (or later)"
fi

mkdir -p licenses
{
  echo "FFmpeg used by Wallpaper"
  echo "======================================="
  echo
  echo "This file is generated by tools/ffmpeg-notice.sh from the libraries that are actually in the"
  echo "tree. Regenerate it after tools/get-ffmpeg.sh; do not hand-edit it."
  echo
  echo "What we use it for"
  echo "------------------"
  echo "  Demuxing and decoding video wallpaper files (libavformat + libavcodec). The code that calls"
  echo "  it is Engine/Graphics/FFmpegPlayer.cpp. No FFmpeg source is copied into this project; the"
  echo "  library is used through its public headers and linked as shared DLLs."
  echo
  echo "The build, as the build itself reports it"
  echo "-----------------------------------------"
  echo "  version      : $VER_LINE"
  echo "  effective    : $EFFECTIVE"
  echo "  license, in the library's own words:"
  echo "$LICENSE" | sed 's/^/    /'
  echo "  configuration: $CONF"
  echo
  echo "  The license text itself is shipped next to this file as LICENSE-FFmpeg.txt, taken from the"
  echo "  same archive (its header line reads: $(head -1 "$DIR/LICENSE.txt" 2>/dev/null | tr -s ' ')$(sed -n '2p' "$DIR/LICENSE.txt" 2>/dev/null | tr -s ' '))."
  echo
  echo "The libraries that ship (copied next to WallpaperRenderer.exe by CMake)"
  echo "----------------------------------------------------------------------"
  # Taken from the CMake staging list, not from the SDK's bin/ - that directory also holds avdevice and
  # avfilter, which we never link and must not claim to distribute.
  FAMS=$(grep -oE 'foreach\(lib [a-z ]+\)' CMakeLists.txt | head -1 | sed 's/foreach(lib //; s/)//')
  [ -n "$FAMS" ] || { echo "REFUSE: could not read the staged DLL families out of CMakeLists.txt"; exit 2; }
  for f in $FAMS; do
    d=$(ls "$DIR/bin/$f"-*.dll 2>/dev/null | head -1)
    [ -n "$d" ] || { echo "REFUSE: CMake stages $f but $DIR/bin has no $f-*.dll"; exit 2; }
    echo "  $(basename "$d")"
  done
  echo
  echo "Where to get the corresponding source"
  echo "-------------------------------------"
  echo "  Binary archive we downloaded:      $URL"
  echo "  Archive sha256:                  ${ZIP_SHA:-not recorded - build/ffm-dl/*.zip was cleaned away}"
  echo "  The FFmpeg commit it was built from: ${COMMIT:-unknown} (read out of the version line above)"
  echo "    https://github.com/FFmpeg/FFmpeg/commit/${COMMIT:-}"
  echo "    https://git.ffmpeg.org/ffmpeg.git  (release branch ${SRC_TAG:-n/a})"
  echo "  Build scripts that produced it:    https://github.com/BtbN/FFmpeg-Builds"
  echo
  echo "  Caveat worth knowing: the archive URL sits under the upstream \"latest\" release tag, which is"
  echo "  a rolling tag - it can stop resolving as newer builds appear. The version string and the"
  echo "  commit above are the stable identifiers for the exact bytes we ship, and they are what the"
  echo "  renderer prints at start (and in \`--ctl status\` field \"ffmpeg\")."
  echo
  echo "Replacing the library"
  echo "-------------------"
  echo "  WallpaperRenderer.exe loads these DLLs by name at process start and calls nothing else from"
  echo "  them, so you may swap any av*-*.dll / sw*-*.dll in the program folder for another build of the"
  echo "  same library. That is the point of linking dynamically: the relinked version runs, and the"
  echo "  log and \`--ctl status\` print whichever build was actually loaded."
  echo
  echo "Our obligations under that license, and where each one is met"
  echo "------------------------------------------------------------"
  echo "  1. Ship the license text ............ LICENSE-FFmpeg.txt next to the exe (staged by CMake)."
  echo "  2. Say which library build is used .. this file, plus the version/license/configuration that"
  echo "                                        the renderer logs on start and reports in status.ffmpeg."
  echo "  3. Permit modification/relinking .... shared DLLs, drop-in replaceable (above)."
  echo "  4. Provide or offer the source ...... the three URLs above; the archive URL is the pinned one"
  echo "                                        we downloaded, so it is the exact corresponding binary."
  echo "  5. No GPL or nonfree code ........... this file is refused by the script if the configuration"
  echo "                                        contains --enable-gpl or --enable-nonfree."
} > "$OUT"
echo "wrote $OUT ($(wc -l < "$OUT") lines)"
grep -E "^  (version|license|effective)" "$OUT" | sed 's/^/  /'
